### ISSUE TITLE
[example/python/ssdv2.py] update request in the future release

### ISSUE THREAD

**Issue by okawaj9** [Microchip-Vectorblox/VectorBlox-SDK#1]
1. Accept some input image size and resize output image (tag 1.2.1 - fixed output_scale as "output_scale = 1024. / 300")
2. Print out "Bandwidth (model.get_bandwidth_per_run())" and "Elapsed time (model.get_bandwidth_per_run())" information as same as other python examples

Best Regards.

**Comment by cirqueit** [comment]
In the upcoming release (1.3) we will print out bandwidth and time, along with variable input  size (if model was trained with different inputs). 

Output image size should be easy to modify for a user.
