### ISSUE TITLE
How to use soc-c example with icicle-kit?

### ISSUE THREAD

**Issue by fabiorafaelcoutada** [Microchip-Vectorblox/VectorBlox-SDK#14]
Hello,

After analyzing the last update to VectorBlox-SDK, the sos-c example has a device tree overlay that contains:

- scale@60040000

- warp@60050000

- draw@60060000

As far as I understood, these are generated usinf smarhls, right?

So, my question is: How can i use this example if MPFS_ICICLE_KIT_REFERENCE_DESIGN.tcl can only accept either SMARTHLS or VECTORBLOX and not both of them?

**Comment by cirqueit** [comment]
You can ignore the `scale` `warp` and `draw` components in the icicle overlay. They don't exist in the icicle design (only the core vectorblox instance does).

I'll remove the reference in the next release.

**Comment by fabiorafaelcoutada** [comment]
Okay, got it. But with that answer I have one other question: has anybody from microchip tested the soc-c example?

It's not working stating linking problems with that image.c file...

**Comment by cirqueit** [comment]
Please use 1.4.3 for Icicle Kit, as we haven't released a build compatible w/ 1.4.4

> The `hdmi` command is a helper command for the [SoC Videokit](https://github.com/Microchip-Vectorblox/VectorBlox-SoC-Video-Kit-Demo) that manually toggles the frame buffer to quickly check if HDMI I/O is working (where it's noted at the end of the README).

> Appreciate the feedback as our demos move from early-access to release.

**Comment by fabiorafaelcoutada** [comment]
Okay, got it.

But as I said, version 1.4.3 is not working. The example as it is, it's not compiling. That image.c (that in reality should be called example.c, taken from a random place and putted into the example with that name) as linkage problems. Already lost more than enough time trying to work with a product that never worked in the first place.


What is the correct course of action? Did you test the example inside an icicle kit? if yes, do you have it compiled with buildroot? Do you have it working with yocto? Why including that device tree overlay with all those extra peripherals, if it's not working?

I'm sorry for what I'm about to say, but this is what I told my team last week: "it seems that Microchip went on vacations and ignored that this is a commercial product and uploaded malfunctioning code to the repo, it's the only explanation for such confusing code and git history".

I'm behind schedule by a lot. Now, I don't really know what I need to do. You made the impossible, make version 1.4.3 a perfect release, if compared with 1.4.4.

I spent the last weekend and these last two days, trying to refactor the TCL script for the SOC-Videokit to work with icicle. I never touched a software stack that is being sold has a functioning product with so much problems like this one...

What should be my course of action, now that I'm taking everything I did since vesion 1.4.4 came out to the garbage bin?

I'm sorry about these words, but I'm completely frustrated with your teams: Libero has crazy memory leaks, always crashing, your examples for VectorBlox are broken, your documentation has at least two or three different versions for any topic.... I'm not payed to waste time trying to fix software that is sold as a commercial product....

**Comment by fabiorafaelcoutada** [comment]
"Note: You cannot use the Icicle Kit for the video demo. This is a video-streaming demo and there is no HDMI I/O on the Icicle Kit." I'm not that stupid. When I said refactoring I was saying replicating stuff, without HDMI, and so on, trying the maximum to have a functional example...

You still did not answer my main question: is the soc-c example working? Did anyone from Microchip test that one?

"Our [SoC VideoKit repo](https://github.com/Microchip-Vectorblox/VectorBlox-SoC-Video-Kit-Demo) and [non-SoC repo](https://github.com/Microchip-Vectorblox/VectorBlox-Video-Kit-Demo) have just been made public." I could care less about those two repos added. The main one was there since three weeks ago with that crazy update with the devicetree overlay. Sometimes I think I'm dealing with a Junior developer that does not document code, does not test code, does not creates documentation. 

I think I already have my ansswer: nothing is working.

I just wan't to know: is anything working? Due to the lack of a direct answer, I expect that everything is broken.

So, is the soc-c example ready to be compiled an uploaded to the icicle kit or not?

**Comment by fabiorafaelcoutada** [comment]
Just to be extra sure:

The soc-video-c has this struct:
![image](https://github.com/Microchip-Vectorblox/VectorBlox-SDK/assets/48058032/495744bf-3329-4b0e-a885-863859076c19)

And, then there's this amazing screenshot from the VectorBlox_Video_Kit_Demo_Guide.pdf:
![image](https://github.com/Microchip-Vectorblox/VectorBlox-SDK/assets/48058032/a9cec525-f4eb-4ac9-b152-f7d5d9c7fac8)

I have to ask: Does anyone in Microchip knows what they are doing? Explain to me the difference in those two screenshots I uploaded. I'm starting to feel like you're playing with your costumers. How is this even possible????

Please, be more professional. I'm wasting so much time with this

My god this is the worse software stack I ever laid hans on...
