### ISSUE TITLE
generate_vnnx failed with Resnet50 ONNX model 

### ISSUE THREAD

**Issue by kolabit** [Microchip-Vectorblox/VectorBlox-SDK#16]
I have ONNX model, with Resnet50 based model, and try creating VNNX file with VBX SDK 1.4.4.1
ONNX file generated from PyTorch application with torch.onnx.export() function:

```
if hasattr(model,'transform_input'):
    model.transform_input = False

x = torch.randn(1,3,224,224)
model = model.to("cpu")
torch.onnx.export(model, x, 'mms-rn50-ort.onnx',  input_names = ['input'],  output_names = ['output'])  
```

I follow the steps from tutorial "torchvision_resnet50.sh", and at the last step generate_vnnx shows an error:

```
(vbx_env) (base) kola@Kola-AMD-PC:~/sources/VectorBlox-SDK/VectorBlox-SDK-release-v1.4.4.1$ generate_vnnx -x mms-rn50-ort.xml  -c V1000 -f /home/kola/sources//Training/paper_caps/test/unknown/  -o mms-rn50-ort.vnnx
Traceback (most recent call last):
  File "/home/kola/sources/VectorBlox-SDK/VectorBlox-SDK-release-v1.4.4.1/vbx_env/bin/generate_vnnx", line 33, in <module>
    sys.exit(load_entry_point('vbx', 'console_scripts', 'generate_vnnx')())
  File "/home/kola/sources/VectorBlox-SDK/VectorBlox-SDK-release-v1.4.4.1/python/vbx/vbx/generate/__main__.py", line 20, in main
    generate_vnnx(args.xml,
  File "/home/kola/sources/VectorBlox-SDK/VectorBlox-SDK-release-v1.4.4.1/python/vbx/vbx/generate/vnnx_flow.py", line 82, in generate_vnnx
    json_string = onnx_to_json.run_generate_graph(onnx_model_post, onnx_stats, io_info, image, inline_depthwise=True, remove_nops=True)
  File "/home/kola/sources/VectorBlox-SDK/VectorBlox-SDK-release-v1.4.4.1/python/vbx/vbx/generate/onnx_to_json.py", line 1191, in run_generate_graph
    graph_mxp = generate_mxp_graph(model_src, activations, stats, nodes[0].name, nodes[-1].name, io_info, input_type, ignore_strides, inline_depthwise, remove_nops)
  File "/home/kola/sources/VectorBlox-SDK/VectorBlox-SDK-release-v1.4.4.1/python/vbx/vbx/generate/onnx_to_json.py", line 926, in generate_mxp_graph
    node = nodes[idx]
IndexError: list index (174) out of range

```
OS is Ubuntu 20.04, Python v3.8.8, PyTorch v1.8.0
Please let me know if any additional info is required.

**Comment by LianVictor** [comment]
Hi kolabit,
Since the model you have is based off the Resnet50 model, would there happen to be any modifications made to that model that involved changing any of the layers/nodes?

I can try to see what caused this issue with the generate_vnnx if you can email me the model that you used.

**Comment by kolabit** [comment]
Hi
I just replaced the last original FC layer by the FC layer with two outputs for the binary classification:

`model = models.resnet50(pretrained=True)`
`model.fc = torch.nn.Linear(model.fc.in_features, 2)`
`model.fc = torch.nn.Sequential(model.fc, torch.nn.Softmax(),)`

Sorry, I can't attach the model. Please download here:
https://drive.google.com/file/d/1RR6CWzYzKgCboRNDczTkSz4bwRKa3oUs/view?usp=sharing

**Comment by LianVictor** [comment]
Hi
In regards to the issue you're having, a fix that is in place would involve rebuilding the SDK after making the following changes:
https://github.com/Microchip-Vectorblox/VectorBlox-SDK/blob/0ead78dae74fdf805f64fa0f4ce3140c4c265f69/python/vbx/vbx/generate/onnx_to_json.py#L924
On that line, change the condition to just `if False:`

This should fix the issue with the error you are seeing with your model. This case triggers due to a Reshape node that isn't being properly recognized in the vnnx generation.

**Comment by kolabit** [comment]
Conversion is fixed, model works with simulation, butt I have problem in HW (Icicle Kit).
I have strangely big graph->data_bytes value, so DMA buffer allocation fails. Maybe something wrong in my code. I will keep you informed

**Comment by kolabit** [comment]
Can you please check if SDK v 1.4.4.1 should work with reference design MPFS_ICICLE_VECTORBLOX_2023_06 on the Icicle kit?

I have seg fault with built-in sample:
```
:~/VectorBlox-SDK-release-v1.4.4.1/example/soc-c# ./run-model ../../fw/firmware.bin ./samples_V500_1.4.4/onnx_resnet18-v1.vnnx ../../tutorials/test_images/oreo.jpg CLASSIFY
Reading model
Done
Model ./samples_[   87.985291] run-model[546]: unhandled signal 11 code 0x2 at 0x0000002ae9c284a0 in run-model[2ae9c12000+1c000]
V500_1.4.4/onnx_[   87.996688] CPU: 1 PID: 546 Comm: run-model Not tainted 6.1.33-linux4microchip+fpga-2023.06 #1
resnet18-v1.vnnx[   88.006673] Hardware name: Microchip PolarFire-SoC Icicle Kit (DT)
 is not sane
[   88.014209] epc : 0000002ae9c284a0 ra : 0000002ae9c286e0 sp : 0000003fdcb248c0
[   88.022651]  gp : 0000002ae9c33b80 tp : 0000003fa3f9e600 t0 : 000000000000002a
[   88.029949]  t1 : ffffffffffffffff t2 : 0000002ae9c333b0 s0 : 0000003fdcb248f0
[   88.037247]  s1 : 0000000000000005 a0 : 0000003f8409a400 a1 : 0000000000000000
[   88.044539]  a2 : 000000000000003d a3 : 0000003f8409a3ff a4 : 0000003f8409a434
[   88.051845]  a5 : 0000003f8409a3ff a6 : 2525252f404b4456 a7 : 0000000000000040
[   88.059163]  s2 : 0000000000000000 s3 : 0000002ae9c2fdd8 s4 : 0000002ae9c1be9e
[   88.066468]  s5 : 0000003fdcb24bf8 s6 : 0000002ae9c2fdd8 s7 : 0000003fa4395cf8
[   88.073775]  s8 : 0000003fa4396050 s9 : 0000002adfc9f300 s10: 0000002adfc2c628
[   88.081083]  s11: 0000002adfc2c598 t3 : 0000002ae9c28ad8 t4 : 0000002ae9c64310
[   88.088383]  t5 : 000000000000005a t6 : 0000003fdcb24408
[   88.093764] status: 8000000200006020 badaddr: 0000003f8409a3ff cause: 0000000000000005
Segmentation fault

```

**Comment by kolabit** [comment]
In short, problem is fixed. 
Unfortunately memory buffer is too small in Icicle ref design, so even Resnet50 will not fit. Resnet18 works OK.

**Comment by kolabit** [comment]
fixed
