### ISSUE TITLE
ultralytics.yolov5m.relu.vnnx can't run at PolarFire SoC Icicle Kit ES

### ISSUE THREAD

**Issue by JCLEE555** [Microchip-Vectorblox/VectorBlox-SDK#19]
Hi
I can use VectorBlox-SDK to generate ultralytics.yolov5m.relu.vnnx correctly,but my device can't read ultralytics.yolov5m.relu.vnnx
![3](https://github.com/user-attachments/assets/7d661ba4-5b44-4f18-a16f-e5dda38d2eea)

My operating environment is as follows：
Hardware:i7-8750H+1050tilaptop 
                PolarFire SoC Icicle Kit ES MPFS250T_ES-FCVG484E
Software:Ubuntu20.04LTS
               Windows 10 pro 22H2 19045.4780
               VectorBlox-SDK-release-v1.4.4.1
For more information,I can run ultralytics.yolov5n.relu.vnnx correctly. But when I try to run ultralytics.yolov5m.relu.vnnx and ultralytics.yolov5s.relu.vnnx, the same problem will come up. I have only changed V1000 to V500 in .sh file to adapt for my FPGA device.
![1](https://github.com/user-attachments/assets/679cb81d-e029-4b1f-96aa-4c3c5b35106d)
ultralytics.yolov5m.relu.sh
![4](https://github.com/user-attachments/assets/fd62ff4a-eca8-48e3-b67d-02eae44c7a2d)
generate ultralytics.yolov5m.relu.vnnx correctly
![5](https://github.com/user-attachments/assets/f55fe379-2d96-4a73-be31-28317e33663c)
run ultralytics.yolov5n.relu.vnnx correctly

**Comment by LianVictor** [comment]
Hi,
The yolov5m.relu.vnnx network is currently too large to be run on the PolarFire SoC Icicle Kit ES.  This is a limitation due to the Yocto Image limiting the u-dma-buf size to 32 MB. Networks that do require more memory than that are not able to be loaded properly on the Icicle Kit.
