### ISSUE TITLE
hyperlink in downloader/README not exists

### ISSUE THREAD

**Issue by LiiNen** [Microchip-Vectorblox/VectorBlox-SDK#3]
To quantize the models, I was looking at the md file, and saw something(the hyperlink) went wrong.

the location of file is at below:
python/third_party/open_model_zoo/tools/downloader/README.md

In line 306 in markdown, target markdown file of hyperlink does not exist.
u can see 404 error when clicking the hyperlink below(the same hyperlink of md file)
[Dataset Preparation Guide](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/datasets.md) 

After checking the issue, please give me some comments.
Best Regards,

**Comment by cirqueit** [comment]
Thanks. We will be updating our tools/links in release 1.3 (coming shortly)
