### ISSUE TITLE
Does VectorBlox-SDK not support quantized model?

### ISSUE THREAD

**Issue by LiiNen** [Microchip-Vectorblox/VectorBlox-SDK#5]
Hi, I tried to upload two tensorflow models-pruned model, pruned with quantization model.

The model with pruning has been successfully converted from h5 to vnnx, so I could upload the hex file on the board.
But the quantized model does not.

I tried in several ways, such as h5 to vnnx, onnx to vnnx and saved_model to vnnx, but none of them be successfully converted.

When using onnx (converted from pb file with using tf2onnx), I got the error message below:
`ERROR:Node model/quant_conv1/conv/StatefulPartitionedCall/StatefulPartitionedCall/Conv2D__7: permutation '[0, 3, 1, 2]' not supported`
It seems like quant layer is not supported, is this right?

How can I convert quantized model to vnnx and hex, with using this sdk?

Best regard,

**Comment by cirqueit** [comment]
Not currently. We currently require an OpenVINO xml/bin file as input into generate_vnnx. You would need to convert to OpenVINO first. We then quantize for our current hardware accelerator.

We will be looking at accepting quantized models directly in the future.
