### ISSUE TITLE
link broken on "more information"- mobilefacenet-arcface

### ISSUE THREAD

**Issue by okawaj9** [Microchip-Vectorblox/VectorBlox-SDK#7]
Current URL of "more information"of mobilefacenet-arcface:
https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/face-recognition-mobilefacenet-arcface/model.yml

This caused "404" web page error.  Can you consider fixing ?

Best Regards,

**Comment by cirqueit** [comment]
Thanks you! `More info` links have been updated in 1.3.3 release
