### ISSUE TITLE
[Tutorial page] Link of "More Information" for "deeplabv3"

### ISSUE THREAD

**Issue by okawaj9** [Microchip-Vectorblox/VectorBlox-SDK#8]
Page: https://github.com/Microchip-Vectorblox/VectorBlox-SDK/tree/master/tutorials
Link of "More Information" for "deeplabv3" is wrongly setting with torchvision.models (https://pytorch.org/vision/0.9/models.html) even though it's tensorflow model (openvino).

Thanks

**Comment by cirqueit** [comment]
Thanks. Fixed in 1.4.1
